### ISSUE TITLE
게시하신 성능 관련

### ISSUE THREAD

**Issue by sooftware** [clovaai/ClovaCall#1]
![image](https://user-images.githubusercontent.com/42150335/79842677-1e30e080-83f4-11ea-904d-2f19c45ef5ab.png)
  
등록해주신 Performance 부분은 에러레이트 기준인가요??  
   
또한 Base와 Full의 차이점이 궁금합니다.

**Comment by jungwoo-ha** [comment]
CER기준이구요 Base가 Release된 데이터셋, Full은 Release 버전에 포함되지 않은 데이터 셋입니다. 자세한 내용은 논문을 참조하시면 되겠습니다.

**Comment by sooftware** [comment]
답변 감사합니다!  
  
저 그리고 또 하나 궁금한 점이 있습니다.  

attention.py 쪽 보면 location-base attention이라고 코멘트 되어 있는데,  
구현하신 코드를 봤을때 저는 attention based models for speech recognition 논문에서 제안한  
Locatioin-Aware (Hybrid) 어텐션이라고 생각했는데, 아닌가요??  
   
아직 논문을 읽어보지 못했는데, 이상하다고 생각되어 질문드립니다.  
   
감사합니다.

**Comment by DevKiHyun** [comment]
@sooftware 네, 맞습니다. attention based models for speech recognition 에서 제안한 어텐션이구요. 명칭에 대한 의문이시면 제안한 논문에서 말한 location-aware 가 맞는 이름입니다. 다만 코드 작성상 적다보니 location-based 라고 적었습니다. 의미상 큰 차이는 없다고 보셔도 됩니다^^.  물론, 저희 논문에선 location-awared attention이라고 제대로 명시해뒀습니다. ㅎㅎ
감사합니다.

**Comment by sooftware** [comment]
답변 감사합니다!
