### ISSUE TITLE
데이터셋 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by HeonKK** [clovaai/ClovaCall#10]
안녕하세요.

한국어 ASR 모델을 돌려보고 싶어 알아보던 도중 ClovaCall 모델을 우연히 알게되어 코드를 돌려보고싶은 학생입니다.

데이터셋을 다운받는 도중 AI Hub쪽 데이터는 받았는데, 아래 링크가 유효하지 않아 모델에서 필요로 하는 데이터셋이 만족되지 않을 것 같다는 생각이 들었습니다.

ClovaAi speech hackathon 2019 data: https://github.com/clovaai/speech_hackathon_2019/tree/master/sample_dataset/train

1. 데이터를 받을 수 있다면 어떤 방법이 있는지
2. AI Hub의 데이터만으로도 학습을 시킬 수 있는지

위 사항에 대한 답변을 받을 수 있을까 해서 문의 드립니다.

**Comment by jungwoo-ha** [comment]
@HeonKK 
안녕하세요? 데이터는 저희 README 신청 링크를 통햬 아카데미 소속 분들께는 데이터 다운 받을 수 있는 링크를 직접 공유 드리고 있습니다. 
https://docs.google.com/forms/d/e/1FAIpQLSf5bm7FtWYeZf8C02mlyZCg32yMrA9_DgKU17oD0migPkEXog/viewform

AI Hub에 공개된 ETRI 데이터는 일상대화 전용으로 학습과 평가는 가능하십니다만 저희 데이터 결과와 비교하시려면 위링크를 통해 신청주셔야 합니다.

**Comment by HeonKK** [comment]
빠른 답변 감사합니다!
참고해서 실행해볼게요.
