### ISSUE TITLE
Hyperparameters max_len 관련 문의

### ISSUE THREAD

**Issue by yddr** [clovaai/ClovaCall#11]
안녕하세요.
공개해주신 코드 실행해보면서 궁금한점이 있어서 문의드립니다.
혹시 Hyperparameters에서 max_len을 80으로 설정하신 이유가 있는건가요?
아니면 그냥 임의의 값인건가요?

**Comment by DevKiHyun** [comment]
max_len은 decoder 에서 training 단계에서 teacher_forcing을 하지 않을때나 inference 같은 경우
 rnn_cell을 몇 번을 돌릴지를 정하는 설정 값입니다.
대체적으론 학습 데이터셋의 경향을 기준으로 설정을 합니다.

80인 경우엔 80개의 character  정도를 포함하는 문장을 만들게 됩니다. 물론, 이후 eos 토큰을 체크하여 실제 의미 있는 문장까지 자르게 됩니다. 

80으로 설정한 것은 ClovaCall의 데이터셋 특성상 대체적으로 짧은 발화를 보여주는 경향이 있기에 문장 길이도 그리 긴 편은 아니여서 설정했던 것 같습니다. 저희 내부 실험에선 다른 데이터셋도 학습시키기 위해서 max_len을 더 크게 잡았던 걸로 기억하는데 자세한 설정값은 기억이 나지 않는군요...

학습에 크게 중요한 부분은 아니지만, 너무 짧거나 너무 길면 학습과 평가에 문제가 될 수 있기 때문에 가급적 사용하는 데이터셋에서의 문장 길이를 고려하셔서 설정하시면 좋을 것 같습니다.

**Comment by yddr** [comment]
친절한 답변 감사합니다!! :)
