### ISSUE TITLE
dataset 구조의 speaker_id 용도

### ISSUE THREAD

**Issue by ghost** [clovaai/ClovaCall#2]
안녕하세요!
우선 좋은 코드와 내용 감사합니다!

Aihub 데이터셋을 이용해서 학습 및 테스트해보려 하는데
ClovaCall 구조를 보던 중에 dataset 구조 json파일에서 speaker_id의 용도가 있을까요??
혹시 unique값이여야 하나요?
Aihub 데이터에서는 어떻게 적용해야할지 고민이 돼서 문의드립니다!

감사합니다!

**Comment by jungwoo-ha** [comment]
@ur-luella 
안녕하세요. speak_id는 발화를 한 사람의 고유 id입니다. 아마 한 id당 최소 수개 최대 20개 정도의 발화가 있을 것 같구요. 데이터 규모가 좀 작긴 한데 speaker recognition 문제에 적용이 가능하지 않을까 생각하고 있습니다. AiHub데이터에는 아마 해당 정보가 없을 것 같네요 ㅎㅎ

**Comment by ghost** [comment]
그렇다면 데이터셋에 해당 정보가 없을 시에 speaker_id는 제가 임의로 적고 코드를 돌려도 되는 걸까요?

**Comment by jungwoo-ha** [comment]
@ur-luella 
없다고하면... 임의로 id를 부여할 수 있겠지만.. 고유 화자별 id를 부여해야 하기 때문에 정보가 잘못 부여되면 극심한 noise 효과를 주게 될 수도 있을 것 같습니다. 음성인식 만을 위한 거라면 저희쪽의 speaker_id 정보를 모델 입력으로 활용하지 않으시는 것이 낫지 않을까 하네요.

**Comment by ghost** [comment]
아 그렇군요..
답변 도움 많이 되었습니다. 감사합니다!
