### ISSUE TITLE
training 시 음성데이터 길이 문의

### ISSUE THREAD

**Issue by ghost** [clovaai/ClovaCall#7]
안녕하세요!
공개하신 모델에서 데이터를 문장단위로 하셨는데
다른 데이터로 training할 때 음성 길이 제한이 있을까요??

**Comment by DevKiHyun** [comment]
@ur-luella 님 안녕하세요!

보통은 문장 단위로 데이터셋을 구성하나
필요에 의해서는 더 길거나 또는 더 짧게 구성하는 것도 가능합니다.

다만, ASR 모델의 구조적 특징 때문에 어느정도 길거나 또는 짧으면 모델의 학습 성능에 영향이 있을 수 있습니다.

**Comment by ghost** [comment]
빠른 답변 감사합니다!! 참고하겠습니다!
