### ISSUE TITLE
논문과 프로젝트 관련 몇 가지 질문드립니다.

### ISSUE THREAD

**Issue by dobby-seo** [clovaai/ClovaCall#9]
안녕하세요. 음성인식 공부중인 학부생입니다.
먼저 좋은 프로젝트 감사드립니다.

몇 가지 질문을 드리고싶은데, 논문 성능을 재구현하려면 학습에 kor_syllable.json 파일의 라벨들을 다 사용하셨을지 궁금합니다.
아래 세가지 특수문자와 발화에서 잘 등장하지 않는 캐릭터도 포함이 되어있는데, 어떤 코퍼스에서 추출된 캐릭터인지 궁금하네요.
e.g.
	"ⓤ",
	"☞",
	"☜",

추가적으로 논문의 QA Call 데이터 셋과 noise 데이터 셋은 어디서 다운로드 받을 수 있는지 여쭤보고 싶습니다.

감사합니다!

**Comment by DevKiHyun** [comment]
안녕하세요. 깃헙을 봐주셔서 감사합니다.

첫번째 질문을 드리자면, 실제로 한국어 코퍼스 상에서 나올 수 있는 글자와 기호들을 다 모으다 보면 예로 들어주신 기호들도 등장하는 경우가 아주 가끔 있었는데요. 그런 부분들까지 다 고려해서 넣었습니다. 다만, 예시에 나오는 정도는 굉장히 적게 나오는 경우라 크게 신경 안쓰셔도 될 것 같습니다. 데이터셋이 여러개이나 등장하는 캐릭터가 서로 다를 수가 있기 때문에 그런 부분들을 고려해서 vocabulary를 합쳤다고 생각하시면 될 것 같습니다.  논문과 동일한 실험을 하실거면 kor_syllable.json을 사용하시는 것이 맞고, 다만 vocab size가 조금 달라진다고 성능에 아주 큰 영향을 주는 것은 아닙니다.

두번째로 QA call 데이터는 네이버의 자체적인 데이터셋 중 하나로 공개가 힘들 것 같습니다ㅠ. Noise의 경우, 원본 데이터셋에 자체적으로 보유한 noise 데이터들을 사용한 것이기 때문에 마찬가지로 공개가 힘들 것 같습니다. (@jungwoo-ha)

궁금하신 것이 있으시다면 언제든 질문 주시기 바랍니다.

**Comment by jungwoo-ha** [comment]
@qute012 
저희 데이터 관심 감사합니다. QA Call은 아쉽지만 사내 직원들의 회사 생활과 시스템 관련 질의 응답데이터로 공개가 어렵구요 ㅎㅎ
noise 데이터도 공개를 함께 하는 것을 고려했다가 바로 정확도 측정에 어려움을 주는 부분이 있어 clean버전만 공개했습니다. 논문 작업을 하신다면 ClovaCall clean버전만으로 해도 괜찮을 것 같습니다.

**Comment by dobby-seo** [comment]
@jungwoo-ha  @DevKiHyun 

답변 감사합니다!

**Comment by BaeKwangho** [comment]
@jungwoo-ha @DevKiHyun 

추가적으로 궁금한 것 질문 드립니다.
혹시 논문에서 aihub 데이터로 학습하고 각 task로 finetuning하는 방법은 aihub를 적절한 loss까지 학습한 모델을 별도의 linear 레이어를 추가하지 않고, lr을 줄여서 학습한게 맞을까요?

**Comment by DevKiHyun** [comment]
@BaeKwangho  넵, 말씀해주신게 맞습니다.
